image: node
cache:
  paths:
  - node_modules
test:
  stage: test
  script:
   - npm install
   - npm test
release:
  stage: deploy
  script:
    - mkdir dist && echo 1 > dist/dist.txt
  artifacts:
    paths:
      - dist
