image: node
cache:
  paths:
  - node_modules
stages:
  - test
  - deploy

test:
  stage: test
  script:
   - npm install
   - npm test

docker:
  image: docker
  services:
    - dokcer:dind
  stage: deploy
  script:
    - docker info
    - docker built -t hello-node .

release:
  stage: deploy
  script:
    - mkdir dist && echo 1 > dist/dist.txt
  artifacts:
    paths:
      - dist
