stages:
  - build

build:
  stage: build
  script:
    - docker build -t hello-node .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker tag hello-node $DOCKER_REGISTRY/gutenye/hello-node:2
    - docker push $DOCKER_REGISTRY/gutenye/hello-node:2
  image: docker
