stages:
  - test
  - deploy
before_script:
  - source scripts/init-ci

test:
  stage: test
  script:
   - npm install
   - npm test
  image: node
  cache:
    paths:
    - node_modules
  environment: testing

docker:
  stage: deploy
  script:
    - docker build -t hello-node .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag hello-node registry.cn-hangzhou.aliyuncs.com/gutenye/hello
    - docker push registry.cn-hangzhou.aliyuncs.com/gutenye/hello
  image: docker
  services:
    - docker:dind

release:
  stage: deploy
  script:
    - mkdir dist && echo 1 > dist/dist.txt
  artifacts:
    paths:
      - dist
  environment: staging
