#!/usr/bin/env bash

main() {
  PORT=3003 npm start
}

build() {
  docker build -t gutenye/hello-node .
}

push() {
  docker push gutenye/hello-node
}

run() {
  docker run --name hello-node -e PORT=80 -p 3003:80 -d  gutenye/hello-node
}

case "$1" in
  "" ) main;;
  build ) build ;;
  push ) push ;;
  run ) run ;;
esac


