#!/usr/bin/env bash

PORT=3005

main() {
  PORT=$PORT npm start
}

build() {
  docker build -t gutenye/hello-node .
}

push() {
  docker push gutenye/hello-node
}

run() {
  docker run --rm --name hello-node -p $PORT:80  gutenye/hello-node
}

case "$1" in
  "" ) main;;
  build ) build ;;
  push ) push ;;
  run ) run ;;
esac


